import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import morgan from 'morgan'
import rateLimit from 'express-rate-limit'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import mongoose from 'mongoose'

const app = express()
const port = process.env.PORT || 4000
const JWT_SECRET = process.env.JWT_SECRET || 'local-development-secret'
const allowedOrigins = (process.env.CLIENT_URL ? process.env.CLIENT_URL.split(',') : ['http://localhost:5173', 'http://localhost:5174', 'http://127.0.0.1:5173', 'http://127.0.0.1:5174']).map((origin) => origin.trim())
app.use(helmet())
app.use(cors({ origin: (origin, callback) => !origin || allowedOrigins.includes(origin) ? callback(null, true) : callback(new Error('Not allowed by CORS')) }))
app.use(express.json({ limit: '1mb' }))
app.use(morgan('dev'))
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 200 }))

const userSchema = new mongoose.Schema({ name: { type: String, required: true, trim: true }, email: { type: String, required: true, unique: true, lowercase: true }, password: { type: String, required: true, select: false }, department: String, rollNumber: String, role: { type: String, enum: ['student', 'admin'], default: 'student' } }, { timestamps: true })
const equipmentSchema = new mongoose.Schema({ equipmentId: { type: String, required: true, unique: true }, name: { type: String, required: true }, category: { type: String, required: true, index: true }, description: String, totalUnits: { type: Number, min: 0, required: true }, availableUnits: { type: Number, min: 0, required: true }, depositAmount: { type: Number, min: 0, default: 0 }, lateFeePerDay: { type: Number, min: 0, default: 0 }, condition: { type: String, default: 'Good' }, status: { type: String, enum: ['active', 'archived', 'maintenance'], default: 'active' }, image: String, qrCode: String }, { timestamps: true })
const bookingSchema = new mongoose.Schema({ borrower: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, equipment: { type: mongoose.Schema.Types.ObjectId, ref: 'Equipment', required: true }, quantity: { type: Number, min: 1, required: true }, borrowDate: { type: Date, required: true }, expectedReturnDate: { type: Date, required: true }, actualReturnDate: Date, status: { type: String, enum: ['pending', 'approved', 'rejected', 'borrowed', 'returned', 'overdue', 'cancelled'], default: 'pending', index: true }, depositPaid: { type: Number, default: 0 }, lateFee: { type: Number, default: 0 }, damageCharges: { type: Number, default: 0 }, refundAmount: { type: Number, default: 0 }, reserved: { type: Boolean, default: false }, transferHistory: [{ fromBorrower: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, toBorrower: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, transferredAt: { type: Date, default: Date.now }, note: String }] }, { timestamps: true })
bookingSchema.index({ equipment: 1, borrowDate: 1, expectedReturnDate: 1, status: 1 })
const User = mongoose.model('User', userSchema)
const Equipment = mongoose.model('Equipment', equipmentSchema)
const Booking = mongoose.model('Booking', bookingSchema)
const memory = { users: [], equipment: [{ _id: 'cam-014', equipmentId: 'CAM-014', name: 'Sony A7 IV', category: 'Cameras', totalUnits: 6, availableUnits: 2, depositAmount: 2500, lateFeePerDay: 100, status: 'active' }, { _id: 'pro-008', equipmentId: 'PRO-008', name: 'Epson EB-X06', category: 'Projectors', totalUnits: 4, availableUnits: 3, depositAmount: 1500, lateFeePerDay: 75, status: 'active' }, { _id: 'aud-022', equipmentId: 'AUD-022', name: 'Rode Wireless GO II', category: 'Audio', totalUnits: 10, availableUnits: 7, depositAmount: 1000, lateFeePerDay: 50, status: 'active' }], bookings: [] }
const useMemory = !process.env.MONGODB_URI

function auth(requiredRole) { return (req, res, next) => { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'Authentication required' }); try { req.user = jwt.verify(token, JWT_SECRET); if (requiredRole && req.user.role !== requiredRole) return res.status(403).json({ error: 'Admin access required' }); next() } catch { res.status(401).json({ error: 'Invalid or expired token' }) } } }
function issueToken(user) { return jwt.sign({ id: user._id, email: user.email, role: user.role, name: user.name }, JWT_SECRET, { expiresIn: '8h' }) }
function populateMemoryBooking(booking) { return { ...booking, borrower: memory.users.find((user) => user._id === booking.borrower), equipment: memory.equipment.find((item) => item._id === booking.equipment) } }

app.get('/api/health', (_req, res) => res.json({ status: 'ok', service: 'av-room-api', persistence: useMemory ? 'memory' : 'mongodb' }))
app.post('/api/auth/register', async (req, res, next) => { try { const { name, email, password, department, rollNumber } = req.body; const normalizedEmail = String(email || '').trim().toLowerCase(); if (!name || !normalizedEmail || !password) return res.status(400).json({ error: 'Name, email and password are required' }); if (password.length < 6) return res.status(400).json({ error: 'Password must be at least 6 characters' }); const hashed = await bcrypt.hash(password, 12); if (useMemory) { if (memory.users.some((entry) => entry.email === normalizedEmail)) return res.status(409).json({ error: 'An account with this email already exists' }); const user = { _id: `user-${Date.now()}`, name: name.trim(), email: normalizedEmail, department, rollNumber, role: 'student' }; memory.users.push({ ...user, password: hashed }); return res.status(201).json({ user: { id: user._id, name: user.name, email: user.email, role: user.role }, token: issueToken(user) }) } const user = await User.create({ name: name.trim(), email: normalizedEmail, password: hashed, department, rollNumber, role: 'student' }); res.status(201).json({ user: { id: user.id, name: user.name, email: user.email, role: user.role }, token: issueToken(user) }) } catch (error) { next(error) } })
app.post('/api/auth/login', async (req, res, next) => { try { const email = String(req.body.email || '').trim().toLowerCase(); const { password } = req.body; const user = useMemory ? memory.users.find((entry) => entry.email === email) : await User.findOne({ email }).select('+password'); if (!user || user.role !== 'student' || !(await bcrypt.compare(password, user.password))) return res.status(401).json({ error: 'Invalid student email or password' }); res.json({ user: { id: user._id, name: user.name, email: user.email, role: user.role }, token: issueToken(user) }) } catch (error) { next(error) } })
app.post('/api/auth/admin/login', async (req, res) => { const email = (process.env.ADMIN_EMAIL || 'admin@avroom.local').toLowerCase(); const password = process.env.ADMIN_PASSWORD || 'admin123'; if (process.env.NODE_ENV === 'production' && (!process.env.ADMIN_EMAIL || !process.env.ADMIN_PASSWORD)) return res.status(503).json({ error: 'Admin credentials are not configured' }); if (String(req.body.email || '').trim().toLowerCase() !== email || req.body.password !== password) return res.status(401).json({ error: 'Invalid admin credentials' }); const user = { _id: 'admin-local', name: 'AV Room Admin', email, role: 'admin' }; res.json({ user, token: issueToken(user) }) })
app.get('/api/equipment', auth(), async (req, res, next) => { try { const filter = { status: 'active', ...(req.query.category && { category: req.query.category }), ...(req.query.search && { $or: [{ name: new RegExp(req.query.search, 'i') }, { equipmentId: new RegExp(req.query.search, 'i') }] }) }; res.json(useMemory ? memory.equipment.filter((item) => (!filter.category || item.category === filter.category) && (!req.query.search || `${item.name} ${item.equipmentId}`.toLowerCase().includes(req.query.search.toLowerCase()))) : await Equipment.find(filter).sort({ name: 1 })) } catch (error) { next(error) } })
app.post('/api/equipment', auth('admin'), async (req, res, next) => { try { const item = useMemory ? { _id: `equipment-${Date.now()}`, ...req.body, availableUnits: req.body.totalUnits } : await Equipment.create({ ...req.body, availableUnits: req.body.totalUnits }); res.status(201).json(item) } catch (error) { next(error) } })
app.patch('/api/equipment/:id/archive', auth('admin'), async (req, res, next) => { try { if (useMemory) { const item = memory.equipment.find((entry) => entry._id === req.params.id || entry.equipmentId === req.params.id); if (!item) return res.status(404).json({ error: 'Equipment not found' }); item.status = 'archived'; return res.json(item) } const filters = [{ equipmentId: req.params.id }]; if (req.params.id.match(/^[0-9a-fA-F]{24}$/)) filters.push({ _id: req.params.id }); const item = await Equipment.findOneAndUpdate({ $or: filters }, { status: 'archived' }, { new: true }); if (!item) return res.status(404).json({ error: 'Equipment not found' }); res.json(item) } catch (error) { next(error) } })
app.post('/api/bookings', auth(), async (req, res, next) => { try { const { equipmentId, quantity, borrowDate, expectedReturnDate } = req.body; const start = new Date(borrowDate); const end = new Date(expectedReturnDate); const requestedQuantity = Number(quantity); if (!Number.isInteger(requestedQuantity) || requestedQuantity < 1 || Number.isNaN(start.valueOf()) || Number.isNaN(end.valueOf()) || end <= start) return res.status(400).json({ error: 'Quantity and a valid return date after the borrow date are required' }); const equipment = useMemory ? memory.equipment.find((item) => item.equipmentId === equipmentId && item.status === 'active') : await Equipment.findOne({ equipmentId, status: 'active' }); if (!equipment) return res.status(404).json({ error: 'Active equipment not found' }); const existing = useMemory ? memory.bookings.filter((item) => item.equipment === equipment._id && ['pending', 'approved', 'borrowed'].includes(item.status) && new Date(item.borrowDate) < end && new Date(item.expectedReturnDate) > start).reduce((sum, item) => sum + item.quantity, 0) : await Booking.aggregate([{ $match: { equipment: equipment._id, status: { $in: ['pending', 'approved', 'borrowed'] }, borrowDate: { $lt: end }, expectedReturnDate: { $gt: start } } }, { $group: { _id: null, quantity: { $sum: '$quantity' } } }]).then((rows) => rows[0]?.quantity || 0); if (existing + requestedQuantity > equipment.totalUnits) return res.status(409).json({ error: 'Requested quantity is not available for those dates' }); const booking = { borrower: req.user.id, equipment: equipment._id, quantity: requestedQuantity, borrowDate: start, expectedReturnDate: end, status: 'pending', depositPaid: equipment.depositAmount * requestedQuantity, reserved: false }; if (useMemory) { const saved = { _id: `booking-${Date.now()}`, ...booking }; memory.bookings.push(saved); return res.status(201).json(saved) } res.status(201).json(await Booking.create(booking)) } catch (error) { next(error) } })
app.get('/api/bookings', auth(), async (req, res, next) => { try { const filter = req.user.role === 'admin' ? {} : { borrower: req.user.id }; res.json(useMemory ? memory.bookings.filter((booking) => !filter.borrower || booking.borrower === filter.borrower).map(populateMemoryBooking) : await Booking.find(filter).populate('equipment borrower').sort({ createdAt: -1 })) } catch (error) { next(error) } })
app.patch('/api/bookings/:id/approve', auth('admin'), async (req, res, next) => { try { const booking = useMemory ? memory.bookings.find((item) => item._id === req.params.id) : await Booking.findById(req.params.id).populate('equipment'); if (!booking) return res.status(404).json({ error: 'Booking not found' }); if (booking.status !== 'pending') return res.status(409).json({ error: 'Only pending bookings can be approved' }); const equipment = useMemory ? memory.equipment.find((item) => item._id === booking.equipment) : booking.equipment; if (!equipment || equipment.availableUnits < booking.quantity) return res.status(409).json({ error: 'Not enough units remain available' }); equipment.availableUnits -= booking.quantity; booking.status = 'approved'; booking.reserved = true; if (!useMemory) { await equipment.save(); await booking.save() } res.json(booking) } catch (error) { next(error) } })
app.patch('/api/bookings/:id/reject', auth('admin'), async (req, res, next) => { try { const booking = useMemory ? memory.bookings.find((item) => item._id === req.params.id) : await Booking.findById(req.params.id); if (!booking) return res.status(404).json({ error: 'Booking not found' }); if (booking.status !== 'pending') return res.status(409).json({ error: 'Only pending bookings can be rejected' }); booking.status = 'rejected'; if (!useMemory) await booking.save(); res.json(booking) } catch (error) { next(error) } })
app.patch('/api/bookings/:id/transfer', auth('admin'), async (req, res, next) => { try { const activeStatuses = ['approved', 'borrowed', 'overdue']; const { name, email, department, rollNumber, note } = req.body; const normalizedEmail = String(email || '').trim().toLowerCase(); if (!name || !normalizedEmail) return res.status(400).json({ error: 'New borrower name and email are required' }); const booking = useMemory ? memory.bookings.find((item) => item._id === req.params.id) : await Booking.findById(req.params.id); if (!booking) return res.status(404).json({ error: 'Booking not found' }); if (!activeStatuses.includes(booking.status)) return res.status(409).json({ error: 'Only active loans can be transferred' }); const previousBorrower = booking.borrower; if (useMemory) { let target = memory.users.find((user) => user.email === normalizedEmail); if (!target) { const hashed = await bcrypt.hash(`transfer-${Date.now()}`, 12); target = { _id: `user-${Date.now()}`, name: name.trim(), email: normalizedEmail, department, rollNumber, role: 'student', password: hashed }; memory.users.push(target) } if (String(previousBorrower) === String(target._id)) return res.status(409).json({ error: 'Loan is already assigned to that borrower' }); booking.borrower = target._id; booking.transferHistory = [...(booking.transferHistory || []), { fromBorrower: previousBorrower, toBorrower: target._id, transferredAt: new Date(), note }]; return res.json(populateMemoryBooking(booking)) } let target = await User.findOne({ email: normalizedEmail }); if (!target) { const hashed = await bcrypt.hash(`transfer-${Date.now()}`, 12); target = await User.create({ name: name.trim(), email: normalizedEmail, department, rollNumber, password: hashed, role: 'student' }) } if (String(previousBorrower) === String(target._id)) return res.status(409).json({ error: 'Loan is already assigned to that borrower' }); booking.borrower = target._id; booking.transferHistory.push({ fromBorrower: previousBorrower, toBorrower: target._id, transferredAt: new Date(), note }); await booking.save(); res.json(await Booking.findById(booking._id).populate('equipment borrower')) } catch (error) { next(error) } })
app.patch('/api/bookings/:id/return', auth('admin'), async (req, res, next) => { try { const booking = useMemory ? memory.bookings.find((item) => item._id === req.params.id) : await Booking.findById(req.params.id).populate('equipment'); if (!booking) return res.status(404).json({ error: 'Booking not found' }); if (!['approved', 'borrowed', 'overdue'].includes(booking.status)) return res.status(409).json({ error: 'Only issued equipment can be returned' }); const equipmentRecord = useMemory ? memory.equipment.find((item) => item._id === booking.equipment) : booking.equipment; const actual = new Date(req.body.actualReturnDate || Date.now()); const expected = new Date(booking.expectedReturnDate); const damageCharges = Math.max(0, Number(req.body.damageCharges) || 0); const delayDays = Math.max(0, Math.ceil((actual - expected) / 86400000)); const fee = delayDays * (equipmentRecord?.lateFeePerDay || 0); booking.actualReturnDate = actual; booking.lateFee = fee; booking.damageCharges = damageCharges; booking.refundAmount = Math.max(0, booking.depositPaid - fee - damageCharges); booking.status = 'returned'; if (booking.reserved && equipmentRecord) { equipmentRecord.availableUnits = Math.min(equipmentRecord.totalUnits, equipmentRecord.availableUnits + booking.quantity); booking.reserved = false; if (!useMemory) await equipmentRecord.save() } if (!useMemory) await booking.save(); res.json({ booking, delayDays, lateFee: fee, damageCharges, refund: booking.refundAmount }) } catch (error) { next(error) } })
app.use((error, _req, res, _next) => { console.error(error); res.status(error.code === 11000 ? 409 : 500).json({ error: error.code === 11000 ? 'A record with that value already exists' : 'Unexpected server error' }) })
if (!useMemory) mongoose.connect(process.env.MONGODB_URI).then(() => app.listen(port, () => console.log(`AV Room API listening on ${port}`))).catch((error) => { console.error(error); process.exit(1) }); else app.listen(port, () => console.log(`AV Room API listening on ${port} using memory mode`))
